// Mocks generated by Mockito 5.4.4 from annotations
// in amaravati_chamber/test/features/theme_mode/presentation/bloc/theme_mode_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:amaravati_chamber/features/theme_mode/domain/use_case/get_or_set_initial_theme_mode_use_case.dart'
    as _i2;
import 'package:amaravati_chamber/features/theme_mode/domain/use_case/set_theme_mode_id_use_case.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GetOrSetInitialThemeModeUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetOrSetInitialThemeModeUseCase extends _i1.Mock
    implements _i2.GetOrSetInitialThemeModeUseCase {
  MockGetOrSetInitialThemeModeUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int execute(_i2.GetOrSetInitialThemeModeUseCaseParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [params],
        ),
        returnValue: 0,
      ) as int);
}

/// A class which mocks [SetThemeModeUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSetThemeModeUseCase extends _i1.Mock
    implements _i3.SetThemeModeUseCase {
  MockSetThemeModeUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void execute(_i3.SetThemeModeUseCaseParams? params) => super.noSuchMethod(
        Invocation.method(
          #execute,
          [params],
        ),
        returnValueForMissingStub: null,
      );
}
